<tr class="notthis caption">
    <th colspan="2">SEO</th>
</tr>
<tr>
    <th>Title</th>
    <td><input type="text" name="url[meta_title]" class="k-input" value="{{url.meta_title}}" /></td>
</tr>
<tr>
    <th>Keywords<span class="k-descr">Maximum 1000 chars (separator ",")</span></th>
    <td>
        <textarea name="url[meta_keys]" maxlength="1000" rows="4" cols="30" class="k-input maxlength" style="width:100%;">{{url.meta_keys}}</textarea>
        <span class="chars_remainer k-descr">Left <strong></strong> /1000</span>
    </td>
</tr>
<tr>
    <th>Page description<span class="k-descr">Maximum 200 chars</span></th>
    <td>
        <textarea name="url[meta_descr]" maxlength="160" rows="3" cols="30" class="k-input maxlength" style="width:100%;">{{url.meta_descr}}</textarea>
        <span class="chars_remainer k-descr">Left <strong></strong> /160</span>
    </td>
</tr>