<tr class="notthis caption">
    <th colspan="2">SEO</th>
</tr>
<tr>
    <th class="trans" data-lang="{{langs.4.id}}">Title</th>
    <td><input type="text" name="url[meta_title_lg2]" class="k-input" value="{{url.meta_title_lg2}}" /></td>
</tr>
<tr>
    <th class="trans" data-lang="{{langs.4.id}}">Keywords<span class="k-descr">Maximum 1000 chars (separator ",")</span></th>
    <td>
        <textarea name="url[meta_keys_lg2]" maxlength="1000" rows="4" cols="30" class="k-input maxlength" style="width:100%;">{{url.meta_keys_lg2}}</textarea>
        <span class="chars_remainer k-descr">Left <strong></strong> /1000</span>
    </td>
</tr>
<tr>
    <th class="trans" data-lang="{{langs.4.id}}">Page description<span class="k-descr">Maximum 200 chars</span></th>
    <td>
        <textarea name="url[meta_descr_lg2]" maxlength="200" rows="3" cols="30" class="k-input maxlength" style="width:100%;">{{url.meta_descr_lg2}}</textarea>
        <span class="chars_remainer k-descr">Left <strong></strong> /200</span>
    </td>
</tr> 