<div class="page">
    <div class="section">
        <div class="tl">
            <div class="cols">
                <div class="lc">
                    <div class="h1">{{dict.REGISTRATION}}</div>
                    {{include (members/frm_register.inc)}}
                </div>
                <div class="fc">
                    <div class="h1">{{dict.AUTH}}</div>
                    {{include (members/frm_login.inc)}}
                </div>
                
                <span class="clear"></span>
            </div>    
        </div>
        <span class="clear" style="height: 100px;"></span>
    </div>
</div>